import type { Config } from "tailwindcss";

const config: Config = {
  darkMode: ["class"],
  content: [
    "./src/pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/components/**/*.{js,ts,jsx,tsx,mdx}",
    "./src/app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  theme: {
    extend: {
      colors: {
        "surface-variant": "#dce3eb",
        "background": "#F4EFEA",
        "surface-tint": "#376847",
        "on-primary": "#ffffff",
        "primary-fixed-dim": "#9dd3aa",
        "secondary": "#994621",
        "on-tertiary-fixed-variant": "#604100",
        "inverse-surface": "#2a3137",
        "error-container": "#ffdad6",
        "on-primary-container": "#f6fff4",
        "on-tertiary": "#ffffff",
        "primary": {
          DEFAULT: "#346645",
          container: "#4d7f5c",
          50: "#eef8f1",
          100: "#d6edd9",
          200: "#b0dbb8",
          300: "#81c38f",
          400: "#55a767",
          500: "#346645",
          600: "#275135",
          700: "#1f412c",
          800: "#193424",
          900: "#142c1e",
        },
        "on-secondary-fixed-variant": "#7a2f0b",
        "secondary-fixed": "#ffdbce",
        "on-tertiary-container": "#fffbff",
        "inverse-on-surface": "#eaf2fa",
        "outline": "#717971",
        "on-background": "#151d22",
        "on-secondary-fixed": "#370e00",
        "on-secondary": "#ffffff",
        "on-primary-fixed-variant": "#1d5031",
        "surface-bright": "#f6faff",
        "on-surface-variant": "#414942",
        "primary-fixed": "#b8efc5",
        "surface": "#FAF7F2",
        "on-tertiary-fixed": "#281900",
        "on-error": "#ffffff",
        "surface-dim": "#d3dbe3",
        "tertiary-container": "#9b6c00",
        "inverse-primary": "#9dd3aa",
        "secondary-fixed-dim": "#ffb598",
        "surface-container-low": "#edf4fd",
        "surface-container-lowest": "#ffffff",
        "surface-container-highest": "#dce3eb",
        "surface-container-high": "#e1e9f1",
        "on-primary-fixed": "#00210e",
        "primary-container": "#4d7f5c",
        "surface-container": "#e7eff7",
        "on-surface": "#151d22",
        "tertiary-fixed-dim": "#fbbb49",
        "secondary-container": "#ff9569",
        "tertiary": "#7b5500",
        "error": "#ba1a1a",
        "outline-variant": "#c0c9bf",
        "on-secondary-container": "#762c08",
        "tertiary-fixed": "#ffdeac",
        "on-error-container": "#93000a",
        "licorice": "#151d22",
        "pewter": "#2D3134",
        "oatmeal": "#F4EFEA",
        "ricepaper": "#FAF7F2",
        "mustard": "#E6A938",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        none: "0px",
        sm: "0.125rem",
        md: "0.25rem",
        lg: "0.5rem",
        xl: "0.75rem",
        full: "9999px",
      },
      spacing: {
        unit: "4px",
        gutter: "16px",
        margin: "24px",
        xs: "4px",
        sm: "8px",
        md: "16px",
        lg: "24px",
        xl: "48px",
      },
      fontFamily: {
        "display-lg": ["Space Mono", "monospace"],
        "headline-md": ["Space Mono", "monospace"],
        "headline-sm": ["Space Mono", "monospace"],
        "body-lg": ["JetBrains Mono", "monospace"],
        "body-md": ["JetBrains Mono", "monospace"],
        "label-bold": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        mono: ["JetBrains Mono", "monospace"],
        sans: ["JetBrains Mono", "monospace"],
      },
      boxShadow: {
        pixel: "2px 2px 0px 0px rgba(21,29,34,1)",
        "pixel-md": "3px 3px 0px 0px rgba(21,29,34,1)",
        "pixel-lg": "5px 5px 0px 0px rgba(21,29,34,1)",
        "pixel-active": "0px 0px 0px 0px rgba(21,29,34,1)",
      },
    },
  },
  plugins: [],
};
export default config;
